name: Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  check_and_execute:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Check for modifications in microservice
        run: |
          for service in config-service; do
            if git diff --name-only HEAD | grep -q "^${service}/"; then
              echo "Changes detected in ${service}"
              cd "${service}" || exit 1
              # Run your commands here for each microservice
              cp ../.env .
              node -v
              npm i
              npm install -g serverless
              npm install --save-dev serverless-plugin-typescript
              serverless deploy --config serverless-dev.yml
              pwd
              ls
              cd ..
            else
              echo "No changes detected in ${service}"
            fi
          done
