name: Deploy Microservices

on:
  push:
    branches:
      - main


jobs:
  check_and_execute:
   runs-on: 
        self-hosted
   steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Setup Node
        run: |
         sudo apt update
         sudo apt install build-essential libssl-dev -y
         curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
         source ~/.bashrc
         source ~/.bash_profile
         export NVM_DIR="/home/ubuntu/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          mkdir bash_profile
         nvm --version
         nvm install 18 -y
         nvm use 18


      - name: Check for modifications in microservice
        run: |
          for service in config-service; do
            if git diff --name-only HEAD | grep -q "^${service}/"; then
              echo "Changes detected in ${service}
              cd "${service}" || exit 1
              # Run your commands here for each microservice
              cp ../.env .
              node -v
              npm i
              sudo apt-get install npm -g serverless
              sudo apt-get install npm --save-dev serverless-plugin-typescript
              serverless deploy --config serverless-dev.yml
              pwd
              ls
              cd ..
            else
              echo "No changes detected in ${service}"
            fi
          done
